# Generates ai-map.json -- the machine-readable cold-start map for AI agents.
# AUTO-GENERATED artifact (GOVERNANCE.md class 3): never hand-edit ai-map.json; run this.
# SSOT-safe: every value is either a POINTER (path) or a field EXTRACTED from its SSOT at
# generation time (with a `source`), never an authored restatement. Regenerating fixes drift.
# Pure ASCII / PowerShell 5.1-safe.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

function Get-Field($text, $label) {
    if ($text -match "(?m)^$([regex]::Escape($label))\s*(.+?)\s*$") { return $matches[1].Trim() }
    return $null
}

$manifestPath = "_ORVION_CANONICAL/manifest.md"
$manifest = Get-Content $manifestPath -Raw

$canonical = @()
foreach ($f in (Get-ChildItem -Path "_ORVION_CANONICAL" -Filter "*.md" | Sort-Object Name)) {
    $c = Get-Content $f.FullName -Raw
    $num = if ($f.Name -match '^(\d\d)_') { [int]$matches[1] } else { -1 }
    $layer = if ($num -ge 0 -and $num -le 23) { "business/domain" }
             elseif ($num -ge 24 -and $num -le 33) { "schema/database" }
             else { "governance/operational" }
    $canonical += [ordered]@{
        path    = "_ORVION_CANONICAL/$($f.Name)"
        version = if ($c -match 'Version:\s*(\S+)') { $matches[1] } else { $null }
        status  = if ($c -match 'Status:\s*(.+)')  { $matches[1].Trim() } else { $null }
        layer   = $layer
    }
}

$map = [ordered]@{
    "_comment"   = "AUTO-GENERATED by scripts/generate-ai-map.ps1 -- do not hand-edit. Machine-readable cold-start map for AI agents. Every value is a pointer or is extracted from its SSOT; the authority is the cited file, never this map. Regenerate to refresh."
    generated_at = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    project      = "ORVION"
    one_liner    = "Travel CRM / operations / revenue platform for Egyptian travel agencies; Supabase/PostgreSQL backend = SQL migrations + app-schema RPCs. No application UI yet."
    boot_order   = @("README.md","AGENTS.md","GOVERNANCE.md","_ORVION_CANONICAL/manifest.md","(active changes/SPEC-*.md, else _ORVION_CANONICAL/32_execution_roadmap.md)")
    live_state   = [ordered]@{
        source                = $manifestPath
        phase                 = Get-Field $manifest "Current Phase:"
        active_change_request = Get-Field $manifest "Active Change Request:"
        last_completed        = Get-Field $manifest "Last Completed:"
        next_capability       = Get-Field $manifest "Next capability:"
    }
    authority = [ordered]@{
        execution_conduct   = "AGENTS.md"
        knowledge_ssot      = "GOVERNANCE.md (section 2 SSOT matrix)"
        cr_state_machine    = "CR_LIFECYCLE.md"
        coding_standards    = "CODING_STANDARDS.md"
        ratified_decisions  = "reports/architecture-decision-records.md"
        accepted_findings   = "reports/master/MASTER_GAP_REGISTER.md"
        deferred_and_triggers = "reports/future-backlog.md"
        schema_truth        = "supabase/migrations/**"
        live_state          = $manifestPath
        file_index          = "repository-index.md"
    }
    verify = [ordered]@{
        start = "npx supabase start"
        reset = "npx supabase db reset"
        smoke = "docker exec -i supabase_db_ORVION psql -U postgres -d postgres -f - < scripts/verify_database.sql  (expect: ALL CHECKS PASSED)"
    }
    canonical_docs = $canonical
    counts = [ordered]@{ canonical_docs = $canonical.Count }
}

$map | ConvertTo-Json -Depth 6 | Out-File "ai-map.json" -Encoding utf8
Write-Host "ai-map.json generated ($($canonical.Count) canonical docs, phase extracted from manifest)."
