Clear-Host

Write-Host ""
Write-Host "===============================" -ForegroundColor Cyan
Write-Host " ORVION Repository Automation"
Write-Host "===============================" -ForegroundColor Cyan
Write-Host ""

Write-Host "[1/8] Refresh Project Tree..."
cmd /c "tree /f /a > project-tree.txt"

Write-Host "[2/8] Refresh Repository Index..."
$indexLines = @(
    "# Repository Index",
    "",
    "Generated by scripts/repository-all.ps1 -- do not hand-edit.",
    "",
    "| Path | Version | Status | Canonical | Layer |",
    "| --- | --- | --- | --- | --- |"
)
$canonicalFiles = Get-ChildItem -Path "_ORVION_CANONICAL" -Filter "*.md" | Sort-Object Name
foreach ($f in $canonicalFiles) {
    $content = Get-Content $f.FullName -Raw
    $version = if ($content -match 'Version:\s*(\S+)') { $matches[1] } else { "-" }
    $status = if ($content -match 'Status:\s*(.+)') { $matches[1].Trim() } else { "-" }
    $canonical = if ($content -match 'Canonical:\s*(\S+)') { $matches[1] } else { "-" }
    $num = if ($f.Name -match '^(\d\d)_') { [int]$matches[1] } else { -1 }
    $layer = if ($num -ge 0 -and $num -le 23) { "business/domain" } elseif ($num -ge 24 -and $num -le 33) { "schema/database" } else { "governance/operational" }
    $indexLines += "| _ORVION_CANONICAL/$($f.Name) | $version | $status | $canonical | $layer |"
}
$indexLines | Out-File "repository-index.md" -Encoding utf8

Write-Host "[3/8] Refresh Git Files..."
git ls-files | Out-File tracked-files.txt -Encoding utf8
git log --graph --decorate --oneline --all | Out-File git-tree.txt -Encoding utf8

Write-Host "[4/8] Stage Changes..."
git add .

Write-Host "[5/8] Repository Status..."
git status --short

$msg = Read-Host "`nCommit message"

if ([string]::IsNullOrWhiteSpace($msg)) {
    Write-Host ""
    Write-Host "Cancelled." -ForegroundColor Yellow
    exit
}

Write-Host ""
Write-Host "[6/8] Commit..."
git commit -m "$msg"

if ($LASTEXITCODE -ne 0) {
    exit
}

Write-Host "[7/8] Push..."
git push

if ($LASTEXITCODE -ne 0) {
    exit
}

Write-Host "[8/8] Done"

$commit = git rev-parse --short HEAD

Write-Host ""
Write-Host "=====================================" -ForegroundColor Green
Write-Host " Repository Updated Successfully"
Write-Host "=====================================" -ForegroundColor Green
Write-Host "Branch : $(git branch --show-current)"
Write-Host "Commit : $commit"
Write-Host ""